export const GET_RECIPES="GET_RECIPES";
export const GET_USER="GET_USER";
export const GET_CATEGORY="GET_CATEGORY";
export const DELETE_RECIPE="DELETE_RECIPE";
export const GET_SHOPPINGLIST="GET_SHOPPINGLIST";
export const ADD_CATEGORY="ADD_CATEGORY";
export const ADD_RECIPE="ADD_RECIPE";
export const ADD_PRODUCT="ADD_PRODUCT";
export const EDIT_RECIPE="EDIT_RECIPE";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const EDIT_COUNT="EDIT_COUNT";


